//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
module table {
	/**
	 * FILE: 炮台.xlsx SHEET: 炮台
	 */
	export class TableBatteryConfig {
		id: number;
		/**
		 * 渔网半径
		 */
		fishNetRadius: number;
		/**
		 * 资源编号
		 */
		resNo: number;
		/**
		 * 发射子弹数量
		 */
		fireBulletNum: number;

		GetType(): string { return 'table.TableBatteryConfig'; }
	}
}
