//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
module table {
	/**
	 * FILE: 鱼阵.xlsx SHEET: 鱼阵 KEY: id
	 */
	export class TableFishTeamConfig {
		id: number;
		/**
		 * 队形
		 */
		fishTeam: TableFishTeamConfig.FishTeamItem[];

		GetType(): string { return 'table.TableFishTeamConfig'; }
	}
	export module TableFishTeamConfig {
		export class FishTeamItem {
			templateId: number;
			offsetX: number;
			offsetY: number;
		}
	}
}
