//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
module table {
	/**
	 * FILE: 玩法基础配置.xlsx SHEET: 玩法基础配置 KEY: level
	 */
	export class TableBaseRuleConfigList {
		/**
		 * 等级
		 */
		level: number;
		/**
		 * 下注额
		 */
		betPointList: number[];
		/**
		 * 跑马灯触发条件
		 */
		noticeTriggers: TableBaseRuleConfigList.NoticeTriggersItem[];

		GetType(): string { return 'table.TableBaseRuleConfigList'; }
	}
	export module TableBaseRuleConfigList {
		export class NoticeTriggersItem {
			id: number;
			statement: string;
			action: string;
		}
	}
}
