//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
module table {
	/**
	 * FILE: 玩法基础配置.xlsx SHEET: 庄玩法配置 KEY: level
	 */
	export class TableBankerRuleConfigList {
		/**
		 * 等级
		 */
		level: number;
		/**
		 * 名称
		 */
		name: string;
		/**
		 * 上庄货币下限
		 */
		upBankerPointMin: number;

		GetType(): string { return 'table.TableBankerRuleConfigList'; }
	}
}
