//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
module table {
	/**
	 * FILE: 房间配置表.xlsx SHEET: Sheet1 KEY: gameId*0xFF
	 */
	export class TableRoomConfig {
		/**
		 * 游戏ID
		 */
		gameId: number;
		/**
		 * 压注筹码列表
		 */
		chipList: TableRoomConfig.ChipListItem[];

		GetType(): string { return 'table.TableRoomConfig'; }
	}
	export module TableRoomConfig {
		export class ChipListItem {
			levelRoom: number;
			chips: number[];
		}
	}
}
