//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
module table {
	/**
	 * FILE: 路径表.xls SHEET: Sheet1
	 */
	export class TableFishPath {
		id: string;
		/**
		 * [[x,y,angle,distNext,distTotal]]
		 */
		pathConfig: TableFishPath.PathConfigItem[];

		GetType(): string { return 'table.TableFishPath'; }
	}
	export module TableFishPath {
		export class PathConfigItem {
			x: number;
			y: number;
			angle: number;
			distNext: number;
			distTotal: number;
		}
	}
}
