//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
module table {
	/**
	 * FILE: 鱼潮表.xls SHEET: Sheet1
	 */
	export class TableFishBoom {
		/**
		 * 鱼潮ID
		 */
		id: number;
		/**
		 * 鱼ID
		 */
		fishId: number;
		/**
		 * 间隔时间
		 */
		intervalTime: number;
		/**
		 * 路径
		 */
		path: string;
		/**
		 * 鱼数量
		 */
		fishNum: number;
		/**
		 * 起始时间
		 */
		beginTime: number;

		GetType(): string { return 'table.TableFishBoom'; }
	}
}
