//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
module table {
	/**
	 * FILE: 玩法配置.xlsx SHEET: 玩法配置 KEY: level
	 */
	export class TableGameRuleConfigList {
		/**
		 * 等级
		 */
		level: number;
		/**
		 * 奖章等级范围
		 */
		medalGrades: number[];
		/**
		 * 本场不会出现的鱼ID
		 */
		banFishids: number[];
		/**
		 * 炸弹鱼范围
		 */
		BurstRange: number;

		GetType(): string { return 'table.TableGameRuleConfigList'; }
	}
}
