//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
module table {
	/**
	 * FILE: 路径表.xls SHEET: Sheet1
	 */
	export class TableFishPath {
		id: string;
		x: number;
		y: number;
		angle: number;
		/**
		 * 下一个点的距离
		 */
		distLast: number;
		/**
		 * 起始点的距离
		 */
		distTotal: number;

		GetType(): string { return 'table.TableFishPath'; }
	}
}
