//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
module table {
	/**
	 * FILE: 鱼表.xlsx SHEET: Sheet1
	 */
	export class TableFishConfig {
		/**
		 * ID
		 */
		sign: number;
		/**
		 * 是否可以锁定
		 */
		lockable: boolean;
		/**
		 * 最大生命值
		 */
		maxLife: number;
		/**
		 * 碰撞范围
		 */
		colliderAry: TableFishConfig.ColliderAryItem[];
		/**
		 * 影片剪辑组
		 */
		movieClipAry: TableFishConfig.MovieClipAryItem[];
		/**
		 * 速度
		 */
		speed: number;
		/**
		 * 杀死鱼的赔率
		 */
		killOdds: number;

		GetType(): string { return 'table.TableFishConfig'; }
	}
	export module TableFishConfig {
		export class ColliderAryItem {
			posX: number;
			posY: number;
			radius: number;
		}
	}
	export module TableFishConfig {
		export class MovieClipAryItem {
			keyName: string;
			groupName: string;
			actionName: string;
		}
	}
}
