//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
module table {
	/**
	 * FILE: 玩法配置.xlsx SHEET: 玩法配置 KEY: level
	 */
	export class TableGameRuleConfigList {
		/**
		 * 等级
		 */
		level: number;
		/**
		 * 历史记录显示个数
		 */
		goodsHistoryCount: number;

		GetType(): string { return 'table.TableGameRuleConfigList'; }
	}
}
